FROM phpdockerio/php71-fpm:latest

# Install selected extensions and other stuff
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install make \
    && apt-get install wget \
    && apt-get -y --no-install-recommends install php7.1-redis php7.1-mysql php7.1-sqlite php-xdebug php7.1-mbstring php7.1-gd  \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*


WORKDIR "/var/www/app"
